[package]
name = "arsy-code"
version.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["wasm"]
dap = []
wasm = ["dep:wasmtime"]
remote-transports = []

[dependencies]
arsy-compat = { path = "../arsy-compat" }
arsy-kernel = { path = "../arsy-kernel" }
arsy-pty = { path = "../arsy-pty" }
cap-std.workspace = true
globset.workspace = true
ignore = "=0.4.23"
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
toml.workspace = true
tree-sitter.workspace = true
tree-sitter-rust.workspace = true
ureq.workspace = true
wasmtime = { workspace = true, optional = true }
yaml_serde.workspace = true

[dev-dependencies]
proptest.workspace = true
rusqlite.workspace = true

[[bench]]
name = "performance"
harness = false

[lints]
workspace = true
